# -*- coding: utf-8 -*-
"""Pandas_Project1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hucyWZzeA7OOSRR0n91Zvx2NXq51AKqU
"""

import kagglehub


path = kagglehub.dataset_download("utkarsharya/ecommerce-purchases")

print("Path to dataset files:", path)

import pandas as pd
import numpy as np

df= pd.read_csv('/content/archive (2).zip')
df

"""Display top 10 rows of the dataset"""

df.head(10)

"""Check last 10 rows of the dataset"""

df.tail(10)

"""Check datatype of each column"""

df.info()

"""or"""

df.dtypes   #it is not a method

"""Check the null values"""

df.isnull()

"""or"""

df.isna()

"""How many rows or columns are there in the dataset"""

df.columns

len(df.columns)

df.info()

"""Highest and Lowest Purchase Price"""

df['Purchase Price'].max()

df['Purchase Price'].min()

"""Average purchase price"""

df['Purchase Price'].mean()

"""How many people have french as their language"""

df.columns

df['Language']

df[df['Language']=='fr']

len(df[df['Language']=='fr'])

df[df['Language']=='fr'].count()

"""Job title contains engineer"""

df['Job']

df[df['Job'].str.contains('engineer',case=False)]  #adding case=False otherwise the code is case sensitive

len(df[df['Job'].str.contains('engineer', case=False)])

"""Find the email of the person with the following ip address:132:207:160:22"""

df.columns

df[df['IP Address'] == "132.207.160.22"]['Email']

"""How many people have mastercard as their credit card provider and made purchases above 50?"""

df.columns

(df['CC Provider']=='Mastercard') & (df['Purchase Price']> 50)

len((df['CC Provider']=='Mastercard') & (df['Purchase Price']> 50))

"""Find email of the person with following credt card no.: 4664825258997302"""

df.columns

df['Credit Card']

df[df['Credit Card']==4664825258997302]["Email"]

"""How many people purchase during am amd how many during pm"""

df.columns

df['AM or PM']

df['AM or PM'].value_counts()

"""How many people have credit cards that expire in 2020"""

df.columns

df[df['CC Exp Date'].apply(lambda x:x[3:]=="20")]

len(df[df['CC Exp Date'].apply(lambda x:x[3:]=="20")])

"""Top 5 most popular email providers(gmail, yaahoo)"""

list1=[]
for email in df ['Email']:
  list1.append(email.split('@')[1])

df['temp']=list1

df['temp'].value_counts()

df['Email'].apply(lambda x:x.split('@')[1]).value_counts().head()

